// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtystgephdueinoourob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0eXN0Z2VwaGR1ZWlub291cm9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MDE3NjksImV4cCI6MjA2NzE3Nzc2OX0.97N8y2C9NmaympgTKYf15gHyp01DvwCOJnQ6R3XPIIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});